# Obtén datos de la API de la Nasa

![imagen](img/nasa.jpg)

Te tendrás que [registrar](https://api.nasa.gov/) y consultar la documentación.

### Importaciones necesarias.

In [2]:
import requests
import json

## Ejercicio 1: Tienes que descargarte la foto de la nasa del día de tu cumpleaños del año pasado, imprimir el título y la descripción.

In [13]:
URL_IMG = "https://api.nasa.gov/planetary/apod"
API_KEY = "2CDvNEVsVkvHgiHGD3ztWsrI7KmcOaEuINlGBSTj"

params = {
    "date": "2025-06-15",
    "api_key" : API_KEY
}

resp = requests.get(URL_IMG, params=params)


if resp.status_code == 200:
    data = resp.json()
    titulo = data.get("title")
    texto = data.get("explanation")
    print(titulo)
    print(texto)

    img = requests.get(data.get("url")).content
    with open("img_nasa.jpg", "wb") as f:
        f.write(img)

    print(data)


else:
    print("error:", resp.json().get("msg"))

Two Worlds, One Sun
How different does sunset appear from Mars than from Earth? For comparison, two images of our common star were taken at sunset, one from Earth and one from Mars. These images were scaled to have the same angular width and are featured here side-by-side. A quick inspection will reveal that the Sun appears slightly smaller from Mars than from Earth. This makes sense since Mars is 50% further from the Sun than Earth. More striking, perhaps, is that the Martian sunset is noticeably bluer near the Sun than the typically orange colors near the setting Sun from Earth. The reason for the blue hues from Mars is not fully understood, but thought to be related to forward scattering properties of Martian dust. The terrestrial sunset was taken in 2012 March from Marseille, France, while the Martian sunset was captured in 2015 by NASA's robotic Curiosity rover from Gale crater on Mars.   APOD Turns 30!: Free Public Lecture in Cork, Ireland on June 24
{'copyright': 'Damia Bouic; \n Right Image Credit:  NASA,\nJPL-Caltech,\nMSSS;\n Digital processing: \nDamia Bouic', 'date': '2025-06-15', 'explanation': "How different does sunset appear from Mars than from Earth? For comparison, two images of our common star were taken at sunset, one from Earth and one from Mars. These images were scaled to have the same angular width and are featured here side-by-side. A quick inspection will reveal that the Sun appears slightly smaller from Mars than from Earth. This makes sense since Mars is 50% further from the Sun than Earth. More striking, perhaps, is that the Martian sunset is noticeably bluer near the Sun than the typically orange colors near the setting Sun from Earth. The reason for the blue hues from Mars is not fully understood, but thought to be related to forward scattering properties of Martian dust. The terrestrial sunset was taken in 2012 March from Marseille, France, while the Martian sunset was captured in 2015 by NASA's robotic Curiosity rover from Gale crater on Mars.   APOD Turns 30!: Free Public Lecture in Cork, Ireland on June 24", 'hdurl': 'https://apod.nasa.gov/apod/image/2506/TwoWorldsOneSun_Bouic_2683.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Two Worlds, One Sun', 'url': 'https://apod.nasa.gov/apod/image/2506/TwoWorldsOneSun_Bouic_1080.jpg'}

## Ejercicio 2: Extraer todos los asteroides que han pasado cerca de la tierra esta última semana. Tenéis que mostrar los datos en un DataFrame, y guardarlos en un CSV.

In [ ]:
URL_AST = "https://api.nasa.gov/neo/rest/v1/feed"
params = {
    "start_date": "2026-05-04",
    "end_date": "2026-05-08",
    "api_key": API_KEY
}

resp = requests.get(URL_AST, params=params)

if resp.status_code == 200:
    data = resp.json()
    json = json.dumps(data, indent= 5)
    print(json)
else:
    print("error:", resp.json().get("msg"))

In [24]:
len(data["near_earth_objects"])

5

In [43]:
lista_ast = []
for i in data["near_earth_objects"]:
    for j in data["near_earth_objects"][i]:
        #print("----------", j)
        info = {
            "id": j["id"],
            "nombre": j["name"],
            "magnitud": j["absolute_magnitude_h"],
            "km": j["estimated_diameter"]["kilometers"]["estimated_diameter_min"],
            "metros": j["estimated_diameter"]["meters"]["estimated_diameter_min"],
            "km": j["estimated_diameter"]["feet"]["estimated_diameter_min"]
        }
        lista_ast.append(info)

print(lista_ast)

[{'id': '3653390', 'nombre': '(2013 VL)', 'magnitud': 27.7, 'km': 25.1501180466, 'metros': 7.6657557353}, {'id': '3719730', 'nombre': '(2015 KB57)', 'magnitud': 22.3, 'km': 302.370924539, 'metros': 92.1626548503}, {'id': '3143095', 'nombre': '(2002 VU114)', 'magnitud': 22.8, 'km': 240.181762721, 'metros': 73.2073989347}, {'id': '3374391', 'nombre': '(2007 HW4)', 'magnitud': 23.6, 'km': 166.1651821003, 'metros': 50.6471458835}, {'id': '3799712', 'nombre': '(2018 DT)', 'magnitud': 27.1, 'km': 33.1543125905, 'metros': 10.1054341542}, {'id': '3461231', 'nombre': '(2009 KR4)', 'magnitud': 25.0, 'km': 87.2047272, 'metros': 26.58}, {'id': '3763274', 'nombre': '(2016 VB1)', 'magnitud': 28.57, 'km': 16.8476770045, 'metros': 5.1351717866}, {'id': '3843898', 'nombre': '(2019 SX)', 'magnitud': 29.6, 'km': 10.4843142043, 'metros': 3.1956188672}, {'id': '3532401', 'nombre': '(2010 MS1)', 'magnitud': 21.89, 'km': 365.2077859922, 'metros': 111.3153296083}, {'id': '3654644', 'nombre': '(2013 XS23)', 'magnitud': 26.3, 'km': 47.92256199, 'metros': 14.6067964271}, {'id': '3802033', 'nombre': '(2018 FZ2)', 'magnitud': 24.3, 'km': 120.3760332259, 'metros': 36.6906137531}, {'id': '2454101', 'nombre': '454101 (2013 BP73)', 'magnitud': 20.45, 'km': 708.8266342193, 'metros': 216.0503511964}, {'id': '3022970', 'nombre': '(1999 SG10)', 'magnitud': 20.76, 'km': 614.5256683901, 'metros': 187.3074177315}, {'id': '3603631', 'nombre': '(2012 JR4)', 'magnitud': 24.0, 'km': 138.2101784897, 'metros': 42.1264610556}, {'id': '3763475', 'nombre': '(2016 VL3)', 'magnitud': 24.42, 'km': 113.9042759761, 'metros': 34.7180222065}, {'id': '3773989', 'nombre': '(2017 HH)', 'magnitud': 19.57, 'km': 1063.0165543388, 'metros': 324.0074353942}, {'id': '3819563', 'nombre': '(2018 HV1)', 'magnitud': 23.1, 'km': 209.1895703015, 'metros': 63.7609789875}, {'id': '3841615', 'nombre': '(2019 HK3)', 'magnitud': 24.7, 'km': 100.1244233463, 'metros': 30.5179232594}, {'id': '3879533', 'nombre': '(2019 UN4)', 'magnitud': 22.8, 'km': 240.181762721, 'metros': 73.2073989347}]

In [44]:
import pandas as pd
df = pd.DataFrame(lista_ast)
df

         id              nombre  magnitud           km      metros
0   3653390           (2013 VL)     27.70    25.150118    7.665756
1   3719730         (2015 KB57)     22.30   302.370925   92.162655
2   3143095        (2002 VU114)     22.80   240.181763   73.207399
3   3374391          (2007 HW4)     23.60   166.165182   50.647146
4   3799712           (2018 DT)     27.10    33.154313   10.105434
5   3461231          (2009 KR4)     25.00    87.204727   26.580000
6   3763274          (2016 VB1)     28.57    16.847677    5.135172
7   3843898           (2019 SX)     29.60    10.484314    3.195619
8   3532401          (2010 MS1)     21.89   365.207786  111.315330
9   3654644         (2013 XS23)     26.30    47.922562   14.606796
10  3802033          (2018 FZ2)     24.30   120.376033   36.690614
11  2454101  454101 (2013 BP73)     20.45   708.826634  216.050351
12  3022970         (1999 SG10)     20.76   614.525668  187.307418
13  3603631          (2012 JR4)     24.00   138.210178   42.126461
14  3763475          (2016 VL3)     24.42   113.904276   34.718022
15  3773989           (2017 HH)     19.57  1063.016554  324.007435
16  3819563          (2018 HV1)     23.10   209.189570   63.760979
17  3841615          (2019 HK3)     24.70   100.124423   30.517923
18  3879533          (2019 UN4)     22.80   240.181763   73.207399

In [45]:
df.to_csv("datos_ast.csv")

## Ejercicio 3. Descargar todos los datos de Sentry Data Service. Es un conjunto de objetos con posibilidad de impactar en la tierra en los próximos 100 años. Guarda todos los posibles en un csv, y muéstrame el que tiene más posibilidades de impactar contra la tierra.

In [60]:
URL_SENTRY = "https://ssd-api.jpl.nasa.gov/sentry.api"

params = {
    "api_key": API_KEY
}

res = requests.get(URL_SENTRY)

print(res)

<Response [200]>

In [54]:
import json

In [76]:
if res.status_code == 200:
    data = res.json()
    data = data["data"]
    df = pd.DataFrame(data)

else:
    print("error:", resp.json().get("msg"))

df.to_csv("sentry_data.csv")

In [77]:
df_nuevo = pd.read_csv("sentry_data.csv")
df

,h,range,ip,des,diameter,last_obs_jd,id,fullname,ps_cum,ps_max,n_imp,ts_max,last_obs,v_inf
0,18.54,2056-2113,8.515158e-07,1979 XB,0.66,2444222.5,bJ79X00B,(1979 XB),-2.69,-2.99,4,0,1979-12-15,23.7606234552547
1,28.45,2060-2122,0.0001203297828,2022 KK2,0.0069,2459722.5,bK22K02K,(2022 KK2),-5.59,-5.79,33,0,2022-05-23,15.5694051293592
2,24.79,2069-2122,0.002743395186,2000 SG344,0.037,2451820.5,bK00SY4G,(2000 SG344),-2.77,-3.11,300,0,2000-10-03,1.35802744453748
3,26.95,2081-2120,1.9442009e-05,2012 VS76,0.014,2456247.5,bK12V76S,(2012 VS76),-5.74,-6.05,15,0,2012-11-16,11.4626328606267
4,26.19,2102-2102,3.772e-09,2018 GN,0.02,2458217.5,bK18G00N,(2018 GN),-8.95,-8.95,1,0,2018-04-09,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140,27.65,2098-2124,0.000611296535,2026 HF2,0.01,2461151.5,bK26H02F,(2026 HF2),-4.47,-4.50,26,0,2026-04-21,17.9093509955688
2141,26.14,2033-2033,4.065e-10,2026 FF3,0.02,2461148.5,bK26F03F,(2026 FF3),-8.85,-8.85,1,0,2026-04-18,20.17
2142,27.30,2118-2122,5.9953e-07,2026 JD1,0.012,2461170.5,bK26J01D,(2026 JD1),-7.55,-8.02,6,0,2026-05-10,13.8796410521575
2143,25.71,2093-2122,2.737508e-06,2026 JK2,0.0242,2461172.5,bK26J02K,(2026 JK2),-5.85,-6.49,25,0,2026-05-12,20.5072923476388
2144,26.66,2119-2124,6.9864e-07,2026 JA,0.016,2461172.5,bK26J00A,(2026 JA),-7.25,-7.50,3,0,2026-05-12,11.7093309859155

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2145 entries, 0 to 2144
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   h            2145 non-null   object
 1   range        2145 non-null   object
 2   ip           2145 non-null   object
 3   des          2145 non-null   object
 4   diameter     2145 non-null   object
 5   last_obs_jd  2145 non-null   object
 6   id           2145 non-null   object
 7   fullname     2145 non-null   object
 8   ps_cum       2145 non-null   object
 9   ps_max       2145 non-null   object
 10  n_imp        2145 non-null   int64
 11  ts_max       2143 non-null   object
 12  last_obs     2145 non-null   object
 13  v_inf        2145 non-null   object
dtypes: int64(1), object(13)
memory usage: 234.7+ KB

In [85]:
df_nuevo["ps_cum"].max()

np.float64(-0.93)

In [89]:
mas_peligroso = df_nuevo["ip"].max()

In [90]:
df_nuevo[df_nuevo["ip"] == mas_peligroso]

,Unnamed: 0,h,range,ip,des,diameter,last_obs_jd,id,fullname,ps_cum,ps_max,n_imp,ts_max,last_obs,v_inf
109,109,28.39,2095-2122,0.102637,2010 RF12,0.0071,2459815.5,bK10R12F,(2010 RF12),-2.97,-2.97,70,0.0,2022-08-24,5.100016