# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [3]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep = "\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [4]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [5]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

### Step 3. Name of the max valued product

In [13]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "").astype(float)

In [14]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [16]:
chipo[chipo["item_price"] == chipo["item_price"].max()]

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

In [17]:
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

In [21]:
filtrado = chipo[chipo["unit_price"] == chipo["unit_price"].max()]
filtrado["item_name"].unique()

array(['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl'],
      dtype=object)

### Step 4. How many products cost more than $10.00?

In [27]:
chipo[chipo["unit_price"]> 10]["item_name"].nunique()

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [30]:
chipo[chipo["unit_price"] > 10]["order_id"].nunique()

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 20$? Es lo mismo?

In [36]:
order_sum = chipo.groupby("order_id")["item_price"].sum()

len(order_sum[order_sum > 20])

566

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [41]:
chipo[chipo["item_price"] > 10]["order_id"].nunique()

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [42]:
chipo["unit_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4        8.49
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: unit_price, Length: 4622, dtype: float64

In [46]:
chipo.loc[:, ["item_name", "unit_price"]].drop_duplicates()

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
3989                          Chicken Salad        8.19
4235                           Chicken Bowl        8.50
4237                    Chips and Guacamole        4.25
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [54]:
chipo.sort_values(["item_name", "choice_description"], ascending= [True, False])

,order_id,quantity,item_name,choice_description,item_price,unit_price
298,129,1,6 Pack Soft Drink,[Sprite],6.49,6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49,6.49
1279,520,1,6 Pack Soft Drink,[Sprite],6.49,6.49
2374,945,1,6 Pack Soft Drink,[Sprite],6.49,6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49,6.49
...,...,...,...,...,...,...
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [66]:
chipo[chipo["unit_price"] == chipo["unit_price"].max()]["quantity"].iloc[0]

np.int64(2)

In [64]:
chipo[chipo["unit_price"] == chipo["unit_price"].max()]

,order_id,quantity,item_name,choice_description,item_price,unit_price
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78,11.89
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89,11.89
613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.78,11.89
749,309,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",11.89,11.89
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89,11.89
1159,478,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89,11.89
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89,11.89
1311,534,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89
1326,541,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89,11.89
1505,612,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.89,11.89
1571,637,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",11.89,11.89
1590,644,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89,11.89
1816,734,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89,11.89
2401,953,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Guaca...",11.89,11.89
2439,969,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89,11.89
2442,970,1,Barbacoa Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.89,11.89
2610,1035,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89
2740,1088,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.89,11.89
2804,1114,1,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.89,11.89
2957,1176,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",11.89,11.89
3120,1244,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89
3208,1283,1,Barbacoa Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89,11.89
3350,1343,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Guacamole, Lettu...",11.89,11.89
3493,1403,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89
3546,1426,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, Guacamole]",11.89,11.89
3749,1499,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89
4239,1692,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",11.89,11.89
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89

In [63]:
chipo[chipo["unit_price"] == chipo["unit_price"].max()].groupby("item_name")["quantity"].sum()

item_name
Barbacoa Salad Bowl     5
Carnitas Salad Bowl     4
Steak Salad Bowl       21
Name: quantity, dtype: int64

In [65]:
len(chipo[chipo["unit_price"] == chipo["unit_price"].max()])

28

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [74]:
chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

In [75]:
len(chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"])

18

### Step 9. How many times did someone order more than one Canned Soda?

In [82]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]

,order_id,quantity,item_name,choice_description,item_price,unit_price
18,9,2,Canned Soda,[Sprite],2.18,1.09
51,23,2,Canned Soda,[Mountain Dew],2.18,1.09
162,73,2,Canned Soda,[Diet Coke],2.18,1.09
171,76,2,Canned Soda,[Diet Dr. Pepper],2.18,1.09
350,150,2,Canned Soda,[Diet Coke],2.18,1.09
352,151,2,Canned Soda,[Coca Cola],2.18,1.09
698,287,2,Canned Soda,[Coca Cola],2.18,1.09
700,288,2,Canned Soda,[Coca Cola],2.18,1.09
909,376,2,Canned Soda,[Mountain Dew],2.18,1.09
1091,450,2,Canned Soda,[Dr. Pepper],2.18,1.09
1092,450,2,Canned Soda,[Coca Cola],2.18,1.09
1944,787,2,Canned Soda,[Dr. Pepper],2.18,1.09
2135,859,2,Canned Soda,[Diet Coke],2.18,1.09
2235,901,4,Canned Soda,[Sprite],4.36,1.09
2905,1156,2,Canned Soda,[Coca Cola],2.18,1.09
2906,1156,2,Canned Soda,[Sprite],2.18,1.09
3152,1258,2,Canned Soda,[Dr. Pepper],2.18,1.09
3364,1349,2,Canned Soda,[Coca Cola],2.18,1.09
3592,1440,2,Canned Soda,[Diet Coke],2.18,1.09
3866,1550,2,Canned Soda,[Mountain Dew],2.18,1.09

In [ ]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]["order_id"].nunique()

1

In [81]:
len(chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)])

20